# Generated by Django 5.0.11 on 2026-03-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertebudget',
            name='seuil',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
