# Generated by Django 5.0.11 on 2026-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_alertebudget_seuil_alter_transaction_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertebudget',
            name='seuil',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
